apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../components/argocd/applicationsets/overlays/default
  - ../../components/argocd/projects/overlays/default
