apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../mlops

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: cluster-config-manager
    path: patch-cluster-config-manager.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: openshift-data-foundation-operator
    path: patch-openshift-data-foundations.yaml
