kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins-tiger
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'cluster-admins-tiger'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
