apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-admins-clusterrolebinding.yaml
  - sandbox-admins-rolebinding.yaml
  - self-provisioner-clusterrolebinding.yaml
